package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"errors"
	"grpcgqlgo/generated/graph/model"
)

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	response := []*model.User{
		{
			ID:    "1",
			Name:  "John Doe",
			Email: "JohnDoe@example.com",
		},
	}

	if len(response) == 0 {
		return nil, errors.New("no users found")
	}
	return response, nil
}
